Encode null email-id to empty string
Gerrit user without an email ID is a valid case. Changes from such a user will result in the following Jenkins exception.

ERROR: java.lang.IllegalArgumentException: Null value not allowed as an environment variable: GERRIT_CHANGE_OWNER_EMAIL

Signed-off-by: Manjunatha Shetty <manjunath.anna@gmail.com>
Change-Id: Ie78c48b5c08fd6cd0926508e0ded314c97befb1c