Create change
GitHub Pull Request: https://github.com/jenkinsci/gerrit-code-review-plugin/pull/76

encode null email-id to empty string

Gerrit user without an email ID is a valid case. Changes from such users will result in the following Jenkins exception.
java.lang.IllegalArgumentException: Null value not allowed as an environment variable: GERRIT_CHANGE_OWNER_EMAIL

Signed-off-by: Manjunatha Shetty <manjunath.anna@gmail.com>

<!-- Please describe your pull request here. -->
encode null email-id to empty string
- [ x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ x] Ensure that the pull request title represents the desired changelog entry
- [ x] Please describe what you did
- [ x] Link to relevant issues in GitHub or Jira
- [ x] Link to relevant pull requests, esp. upstream and downstream changes
- [ x+] Ensure you have provided tests - that demonstrates feature works or fixes the issue

<!--
Put an `x` into the [ ] to show you have filled the information.
The template comes from https://github.com/jenkinsci/.github/blob/master/.github/pull_request_template.md 
You can override it by creating .github/pull_request_template.md  in your own repository 
-->


Patch-set: 1
Change-id: I21d1ce9f721b7e8b53c95c9ffa579d11b6cbca77
Subject: Merge branch 'jenkinsci:master' into bugfix/empty_emails
Branch: refs/heads/master
Status: new
Topic: 
Commit: 3fa7e0b3b5b3104d35735034a2b92602fa60e76c
Tag: autogenerated:gerrit:newPatchSet
Groups: 3fa7e0b3b5b3104d35735034a2b92602fa60e76c
Private: false
Work-in-progress: false