encode null email-id to empty string
Gerrit user without an email ID is a valid case. Changes from such
users will result in following Jenkins exception.
java.lang.IllegalArgumentException: Null value not allowed as an environment variable: GERRIT_CHANGE_OWNER_EMAIL

Signed-off-by: Manjunatha Shetty <manjunath.anna@gmail.com>