Create change
GitHub Pull Request: https://github.com/jenkinsci/gerrit-code-review-plugin/pull/76

encode null email-id to empty string

Gerrit user without an email ID is a valid case. Changes from such users will result in the following Jenkins exception.
java.lang.IllegalArgumentException: Null value not allowed as an environment variable: GERRIT_CHANGE_OWNER_EMAIL

Signed-off-by: Manjunatha Shetty <manjunath.anna@gmail.com>

<!-- Please describe your pull request here. -->
encode null email-id to empty string
- [ x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ x] Ensure that the pull request title represents the desired changelog entry
- [ x] Please describe what you did
- [ x] Link to relevant issues in GitHub or Jira
- [ x] Link to relevant pull requests, esp. upstream and downstream changes
- [ x+] Ensure you have provided tests - that demonstrates feature works or fixes the issue

<!--
Put an `x` into the [ ] to show you have filled the information.
The template comes from https://github.com/jenkinsci/.github/blob/master/.github/pull_request_template.md 
You can override it by creating .github/pull_request_template.md  in your own repository 
-->


Patch-set: 1
Change-id: Ic932fe7d9759494afbbb5b02bad584925d484157
Subject: encode null email-id to empty string
Branch: refs/heads/master
Status: new
Topic: 
Commit: d5a1fab2a938515b0fa6d06aef10a4db06544cf2
Tag: autogenerated:gerrit:newPatchSet
Groups: d5a1fab2a938515b0fa6d06aef10a4db06544cf2
Private: false
Work-in-progress: false